### ISSUE TITLE
[Feature request] Add the app to the F-Droid repo

### ISSUE THREAD

**Issue by Sitavi** [Pool-Of-Tears/GreenStash#1]
Because I, and a lot of people, use F-Droid, it would be very nice to have the app directly in the F-Droid repo. I'm sure that the app will be more popular :)

Is there a technical limitation to that?

**Comment by starry69** [comment]
Yep i was planning to do that, rn I'm working on new update with bunch of improvements and some necessary features such as search bar on home screen, and different tabs for completed and ongoing goals etc, will try to publish on fdroid after that. 
> Is there a technical limitation to that?

I don't think so. Will keep the issue open until then 🤞

**Comment by hyper-ub** [comment]
Why not on play Store

**Comment by starry69** [comment]
status update: I've created a RFP in fdroid data repository https://gitlab.com/fdroid/rfp/-/issues/2125

**Comment by starry69** [comment]
Closing as F-droid has [merged](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11338) the RFP in fdroid data repository, the app should be available in fdroid in one or two days.

**Comment by IzzySoft** [comment]
Congrats to the F-Droid inclusion! Now your app is there I'd usually remove it from my repo within 10 days – unless it was explicitly requested to keep it (see [here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some background). So if you want it to stay, please speak out :wink:

**Comment by IzzySoft** [comment]
OK, will do – just flipped the switch in the config for your app. With the next sync it sill show the hint on its details page that it's available in both places, and link here for details.
