### ISSUE TITLE
For English whites, I hope to add Chinese language

### ISSUE THREAD

**Issue by FMYC2015** [Pool-Of-Tears/GreenStash#10]

**Comment by starry69** [comment]
Thanks! You're very welcome to do so, i think I'll setup a translations platform after merging #9, i suggest please wait until then, I'll give you the translations platform link for the project afterwards.

**Comment by starry69** [comment]
I've set-up translations project at [Poeditor](https://poeditor.com/join/project/e4D68BKjBR) for the app, you can follow the link and get started with your translations now.
