### ISSUE TITLE
Feature request: Schedule backup

### ISSUE THREAD

**Issue by SMSourov** [Pool-Of-Tears/GreenStash#13]
Kindly add "Schedule backup". I think this is the only feature that is missing.

**Comment by starry69** [comment]
Feature does seems nice but problem is for scheduled backups to work, app needs to run a background service 24/7 AFAIK, which checks for set time to take backups and Android is generally hard on memory management so it'll also kill the background service time to time to free up resources if some other app which user is currently interacting with demands it, i.e. some resource heavy video games or something similar, tbh i don't think this makes much sense for app like this.

**Comment by SMSourov** [comment]
I understand.
