### ISSUE TITLE
Feature request: Add currency format when editting amount 

### ISSUE THREAD

**Issue by bramaudi** [Pool-Of-Tears/GreenStash#15]
It seems nice to have auto-format currency while you input the amount.

ie. 1000000 -> 1,000,000

**Comment by starry69** [comment]
Thanks for the suggestion, I'll try whenever i get time.

**Comment by starry69** [comment]
Hi! I've tried multiple methods to achieve this but unfortunately i couldn't find any better way to do it which don't cause issues with decimal formatting, only way to achieve this without having potential decimal formatting bugs is to not allow users to enter amounts in decimal format, which i don't think is a good idea..

I'll see in future if i find some better way to implement it without breaking anything else. Thanks for understanding :)
