### ISSUE TITLE
Crash after adding a goal

### ISSUE THREAD

**Issue by Silverhawk85** [Pool-Of-Tears/GreenStash#2]
Hi when I want to add a new goal the app crashes. From now on the app crashes everytime I restart it.

I use GreenStash v1.1 from F-Droid repository on my Samsung Galaxy A6 Plus with Android 10.

**Comment by starry69** [comment]
Hi! Can you please share logs, you can take logs using `adb logcat --buffer=crash -d > logcat.txt`

**Comment by Silverhawk85** [comment]
> Hi! I've looked into your problem but i was not able to reproduce it, FYI I've tested the app on Android 7.0, 10 & 11, 12 before publishing the release.
> Can you please share the logs, you can take logs using `adb logcat --buffer=crash -d > logcat.txt` Lemme know if you don't know how to use ADB.

I don't know how to use ADB. :)

**Comment by starry69** [comment]
No problem! You can learn & download adb for your system by following [this](https://developer.android.com/studio/releases/platform-tools) link.

Please follow these steps to grab logs.
- enable developer options in your device, go to system > build number & tap continuously 7 times (process may vary between different manufacturers)
- go to developer options and enable USB debugging.
- connect your phone with your computer
- if you're using windows then go to folder in which you've downloaded adb and do shift + right click, a terminal prompt will get opened, enter `./adb logcat --buffer=crash -d > logcat.txt`, adb will make a file named `logcat` in same directory, then you can share that logcat file here. I know it sounds bit complicated but it's actually very simple.

**Comment by Maskross** [comment]
Hei. First of all, I just want to tell you that this is a great job and I'm glad there is finally a FOSS app of this type, so thank you! Second, I am experiencing the same issue with the 1.2 version of the app as well, from the F-Droid repository and using a Samsung Galaxy S20 FE with Android 12. Here is the logcat file.
[logcat.txt](https://github.com/Pool-Of-Tears/GreenStash/files/9014828/logcat.txt)

**Comment by starry69** [comment]
> Hi. First of all, I just want to tell you that this is a great job and I'm glad there is finally a FOSS app of this type, so thank you! Second, I am experiencing the same issue with the 1.2 version of the app as well, from the F-Droid repository and using a Samsung Galaxy S20 FE with Android 12. Here is the logcat file. [logcat.txt](https://github.com/Pool-Of-Tears/GreenStash/files/9014828/logcat.txt)

Thank you for providing logs, it'll be fixed in upcoming update.
