### ISSUE TITLE
Enhancement : Saved amount in percentage 

### ISSUE THREAD

**Issue by Kuladeep1996** [Pool-Of-Tears/GreenStash#20]
Can you add option or include by default to show amount currently saved in percentage as well

**Comment by starry-shivam** [comment]
Good idea! Right now I'm planning to re write UI of the app in jetpack compose (see #18 ) so maybe I'll do it after that, will keep this issue open until then for remainder.

**Comment by starry-shivam** [comment]
This has been added in the source code and should be available with greenstash v2.0 (which is a complete re-write of the application from ground up), if you want, you can join my telegram group to stay in loop with development of v2.0.
