### ISSUE TITLE
[Feature] Mark Deposit Amounts in Green and Withdrawals in Red Color to make it easier to differentiate transaction type in Goal Detail Screen.

### ISSUE THREAD

**Issue by ramakrishnajoshi** [Pool-Of-Tears/GreenStash#25]
Mark Deposit Amounts in Green and Withdrawals in Red Color to make it easier to differentiate transaction type in Goal Detail Screen.

![Screenshot_20230318_145704](https://user-images.githubusercontent.com/36952610/226097246-34b86f9c-9cf2-4996-a2e0-7be0c8d7b283.png)

**Comment by starry-shivam** [comment]
Actually a good idea but i wonder how it'll go along with Material You theming.. what do you think about adding a (+/-) prefixes infront of the amount?
For example:
```
+100
-50
+500
-375
```

It's something other apps like Paytm does too if I'm not wrong.

**Comment by starry-shivam** [comment]
Completed in https://github.com/Pool-Of-Tears/GreenStash/commit/0184731415b44c0d2500af1cc9fd4be94cef6a68
