### ISSUE TITLE
[Feature] Add ability to edit the Note in Goal Detail Screen

### ISSUE THREAD

**Issue by ramakrishnajoshi** [Pool-Of-Tears/GreenStash#26]
Add ability to edit the Note in Goal Detail Screen

**Comment by starry-shivam** [comment]
![IMG_20230318_150459_855](https://user-images.githubusercontent.com/58552395/226097610-20f9fe62-9d88-4f66-bb85-18cd78b6adde.jpg)
Hi! You can edit notes and all other properties by clicking on this pencil icon in the goal card, i don't see a point of adding same thing in multiple screen for no good reason, goal detail screen is supposed to be read-only imo, although I'll probably add ability to delete specific translations there in future updates. Thanks!
