### ISSUE TITLE
Illegal Amount Value Crashes GreenStash

### ISSUE THREAD

**Issue by moriel5** [Pool-Of-Tears/GreenStash#3]
First of all, from my testing (I still haven't truly used the app, I just looked for any bugs I could report to you) I could see that you already did quite a bit to prevent this from happening (I wasn't able to put multiple dots, even via pasting, nor was I able to paste letters, random symbols or Emojis, and putting just zero tells me that the amount is empty).

However when just a single dot is in the amount value, the app crashes when trying to create the goal.

I think that it would be easier to workaround this by bringing up the same toast as when a lone zero is input.

**Comment by moriel5** [comment]
Also inserting a single dot in the deposit and withdraw windows crashes the app.

**Comment by starry69** [comment]
Can confirm, thankyou so much for reporting! it'll fixed in upcoming v1.3 update

**Comment by moriel5** [comment]
Sure, no problem, I'm glad to be of help.

I'll make sure to test version 1.3 when it's out and verify that the big is fixed.

**Comment by moriel5** [comment]
I can verify that this bug is indeed fixed in v1.3, and so far, I have not seen any other bugs.

**Comment by moriel5** [comment]
No problem, if I'll see anything relevant, I'll make sure to report it.
