### ISSUE TITLE
[Feature Request] Importance levels

### ISSUE THREAD

**Issue by Terkyz** [Pool-Of-Tears/GreenStash#35]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

No. But it is useful if I want to have a clearer idea of what I really need to buy or can postpone.

### Describe the solution you'd like

When editing/creating a goal to have an "Importance" button that lets me define a level of importance, such as; "Low", "Medium" and "High" and that (although on second thought, this may generate a conflict in the interface, perhaps it is also necessary to implement a system of sorts) organize the goals from most important to least important, or of course, leaving it blank that is less than less "Low".

### How will you/everyone benefit from this feature?

To be able to have a clearer goal of what is important and what is not.

**Comment by starry-shivam** [comment]
Intresting idea! I'm bit busy right now but will try to implement this in upcoming updates :)

**Comment by Terkyz** [comment]
I would like to add that if a sorting system were implemented, it would be absolutely great to have the ability to sort from lowest to highest price and vice versa.

**Comment by starry-shivam** [comment]
Yep, will add shorting method too when i add this feature.
