### ISSUE TITLE
[Feature Request] Remove Deadline

### ISSUE THREAD

**Issue by seniorm0ment** [Pool-Of-Tears/GreenStash#38]
The ability to simply remove the deadline after setting one would be nice.

**Comment by starry-shivam** [comment]
Makes sense, will probably add an option to do so by long pressing on deadline in edit screen.

**Comment by starry-shivam** [comment]
For anyone who is creating new issue happen to see this and ends up deleting issue template aswell, please don't! They're there for a reason and you should follow them.

**Comment by seniorm0ment** [comment]
Thanks
And as I stated in the other issue, Fasthub does not show the templates unfortunately so I did not know there was a template at the time of creation. Apologies again.
