### ISSUE TITLE
After installing and adding a goal it crashes

### ISSUE THREAD

**Issue by d4f5409d** [Pool-Of-Tears/GreenStash#4]
Android 12, OxygenOS, OnePlus 8, App version 1.3

**Comment by starry69** [comment]
Sorry to hear that! Can you please provide logs? See #2 if you don't know how to take logs via adb.

**Comment by d4f5409d** [comment]
https://send.vis.ee/download/cf51534bbbf7a0ca/#mSYo_N1K8IwYKfxwMzigYg

**Comment by starry69** [comment]
Thanks, can you test this apk build I'm sending now, and try recording the logs again? release builds have `minifyEnabled` set to `true` so it renames all the classes and other files present in source code with some random letters to reduce apk size, unfortunately this also makes harder to debug something cause i can't know where the error is occurring exactly.

**Comment by starry69** [comment]
Make sure to uninstall currently installed release build, otherwise you won't be able to install it due to signature mismatch.

**Comment by d4f5409d** [comment]
https://send.vis.ee/download/58e766d009071da6/#fT3SM3z_KRB53EWmEfksLg

**Comment by starry69** [comment]
> https://send.vis.ee/download/58e766d009071da6/#fT3SM3z_KRB53EWmEfksLg

Looks like link got expired :)

**Comment by d4f5409d** [comment]
Somebody else downloaded it

Agh FUCK

**Comment by d4f5409d** [comment]
What's your Matrix ID?

**Comment by starry69** [comment]
> What's your Matrix ID?

Sorry i don't use matrix, you can send me logs via email if you want `starry369126@outlook.com` or via telegram `@starryboi`.

**Comment by d4f5409d** [comment]
The password for the encrypted e-mail is either: 0UF9GhyOxxvSjZ*x*RWW%nh
or P6%yXjX1IZ@ld^Pc4Y$4OBD
or F@t&dPFyrlEENax2sYgBgKB
or b8THPJ5@W#Y9vx6ddn*&8Dt
I don't know I did write here down but forgot to send it and shat my computer.

**Comment by starry69** [comment]
Tried, none of them worked... Why don't you just send me same link in email which you sent here but someone else download it first, ofcourse that won't happen from my mailbox

**Comment by d4f5409d** [comment]
Ok

**Comment by d4f5409d** [comment]
Ok

**Comment by starry69** [comment]
Thanks, I've received your logs! I'll be giving you a test build here after sometime, please try and see if the issue still occurs with that.

**Comment by starry69** [comment]
Download "app-debug.apk" with Send: simple, safe file sharing https://send.vis.ee/download/1e9d70d950046e53/#mI58fRcW4x_HjyZM7NVdSQ

Please try that out and see if issue still persists

**Comment by d4f5409d** [comment]
Thank you, it now works as expected. :)

**Comment by starry69** [comment]
Awesome! I'll release new version with the fix in few hours.

**Comment by starry69** [comment]
Awesome! I'll release new version with the fix in few hours.

**Comment by d4f5409d** [comment]
Hey man, thank you ❤️
