### ISSUE TITLE
[Feature Request] Adding automatic x amout of money, and notifications

### ISSUE THREAD

**Issue by laaledesiempre** [Pool-Of-Tears/GreenStash#45]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

I always have to add manually money that i want to be added each day automaticly, and i have no notification to remember to do it by the app. so i have to use other aplications for that

### Describe the solution you'd like

It would be awesome to add the posibility of making an auto add money or just a notification to remember you to add money once on x time to your goal. for example, i use the app to track my dialy use of money, adding the amout of money that i can use each day, it would be awesome if it hasppens automatic. auto save money, but only if you open the notification and put "yes i saved the money" or something like that. of course, as something opcional, not by default

### How will you/everyone benefit from this feature?

For people that easly forget things like me, it really practic. 

### Additional context

thanks for this awesome app! <3

**Comment by starry-shivam** [comment]
Seems like a good idea, i think it would make sense to have daily reminder (as a notification) on goals with high priority and maybe weekly reminder with goals having normal priority. What do you think?

**Comment by laaledesiempre** [comment]
First thanks for answering, it seems that you really want to improve the app and i'm really happy of that.
second, maybe custom reminders, but that automaticly add a notification ONLY if you want to, in the create goal manu add the feature to ask for a reminder, weekly (select day and select hour), dialy (select hour),
when you create a new goal, there is a chek mark to add a reminder, if you check that, by default (if priority is high) reminds you every day at (current hour)  but you can set it. and if its normal, by default reminds you every week, in the current day in current hour. but you can change that, even if you want, you can change the default value in options, "default for high priority" and "default for normal priority". if the user want to change that. he could.

also you can add "recomended" amunt of money to put every day based on dialy saving recomendartion. that feature is awesome, i really liked.

have a nice day and sorry for my poor english,
________________________________
De: Strry Shivm ***@***.***>
Enviado: lunes, 26 de junio de 2023 13:23
Para: Pool-Of-Tears/GreenStash ***@***.***>
Cc: laaledesiempre ***@***.***>; Author ***@***.***>
Asunto: Re: [Pool-Of-Tears/GreenStash] [Feature Request] Adding automatic x amout of money, and notifications (Issue #45)


Seems like a good idea, i think it would make sense to have daily reminder (as a notification) on goals with high priority and maybe weekly reminder with goals having normal priority. What do you think?

―

**Comment by starry-shivam** [comment]
Hmm good suggestions, thanks!
Recommend amount is also a nice Idea, I'll try to work on these features somewhere around next month after i come back from my trip. Have a good day ✌️

**Comment by laaledesiempre** [comment]
Good luck in your trip and also have a nice day ❤️
________________________________
De: Stɑrry Shivɑm ***@***.***>
Enviado: miércoles, 28 de junio de 2023 0:00
Para: Pool-Of-Tears/GreenStash ***@***.***>
Cc: laaledesiempre ***@***.***>; Author ***@***.***>
Asunto: Re: [Pool-Of-Tears/GreenStash] [Feature Request] Adding automatic x amout of money, and notifications (Issue #45)


Hmm good suggestions, thanks!
Recommend amount is also a nice Idea, I'll try to work on these features somewhere around next month after i come back from my trip. Have a good day ✌️
