### ISSUE TITLE
about paypal address

### ISSUE THREAD

**Issue by ghost** [Pool-Of-Tears/GreenStash#50]
@starry-shivam 
* fdroid app lists https://www.paypal.com/paypalme/starryrays
* i am unable to find it in readme history [ my search might be inadequate ]
* is paypal address still valid?

**Comment by starry-shivam** [comment]
Sorry, no, that PayPal account is dead as they've banned it, I've tried multiple times to get in touch with PayPal to provide reasoning behind the ban but they never responded so i just gave up and settled with GitHub sponseres instead for donations. I don't know how to update it on F-Droid now maybe I'll try creating an issue sometimes later on F-Droid Gitlab about it.

**Comment by starry-shivam** [comment]
Update: I've created a [merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13455) in F-Droid data repository to get this fixed.
