### ISSUE TITLE
AuthorWebSite & Donate on fdroid metadata

### ISSUE THREAD

**Issue by ghost** [Pool-Of-Tears/GreenStash#53]
hello @starry-shivam again
* i am in process of fixing my mistakes, kindly please look into the following_
* **without your explicit consent** AuthorWebSite ```https://starry-shivam.github.io``` from 
```https://github.com/starry-shivam``` and Donate```https://github.com/Pool-Of-Tears/GreenStash#donations``` given in repo was updated by me in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.starry.greenstash.yml)
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417) and [suggestion](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..
* should i remove it?

**Comment by starry-shivam** [comment]
> should i remove it?

Nope, i don't have any problems with it, thanks for updating the links :)
