### ISSUE TITLE
[Feature Request] Replace/change top bar menu

### ISSUE THREAD

**Issue by mrghosti3** [Pool-Of-Tears/GreenStash#57]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

Currently menu is only exposed after clicking the burger button at the top left corner of the screen. This is inconvenient for one-hand use and you either have to include another hand or change how you hold your phone to quick access the menu.

### Describe the solution you'd like

Replace top bar with something like bottom bar or the slide-able menu replaced with bottom navigation bar. This issue would need more discussion on which option is better.

### Option A (Bottom bar, example 1)

This would completely replace top bar by moving it to the bottom. On the left would be 3 buttons: burger menu, filter, search, and on the right the plus would be for new goals.

The burger menu would could expand a scroll-able menu.

### Option B (Navigation bar, example 2)

This doesn't replace the top bar, but would just remove burger menu as a row of buttons with page icons and their names. The rest of top bar would stay the same.

### Examples
1. https://m3.material.io/components/bottom-app-bar/guidelines#a1332bc2-701f-4234-93e9-ccc2470434d6
2. https://m3.material.io/components/navigation-bar/overview

### How will you/everyone benefit from this feature?

Easier navigation to other pages as the menu would quickly accessed by one hand at the bottom. No matter if the user is left or right handed.

**Comment by starry-shivam** [comment]
I like the bottom navigation bar idea, it'll also make it easy to organise/add the other feature you suggest in #56

**Comment by mrghosti3** [comment]
Yeah, now after coming back with fresh eyes, I do think it's best to go with nav bar. Plus I think it this should be doable much faster than the _Option A_.

**Comment by starry-shivam** [comment]
Indeed, it'll also allow us to organise additional features apart from saving tracker efficiently.

**Comment by mrghosti3** [comment]
Could specify in which commit is this fixed? I check and the top bar with the side menu is still in the app.

**Comment by starry-shivam** [comment]
@mrghosti3 I actually dropped the idea. I personally don't think side panel-based navigation looks that bad or causes any major issues, to be honest. Also, you don't really need to access the navigation drawer that frequently because all of the major functionality is available on the home screen. You only need to access the navigation drawer when updating settings or creating backups, which I don't think you need to do on a daily basis.
