### ISSUE TITLE
[Feature Request] Be able to not add a deadline date

### ISSUE THREAD

**Issue by Terkyz** [Pool-Of-Tears/GreenStash#6]
Basically that, when adding price and name details, if I press "save goal" the goal is saved without a date limit

Thanks for this amazing app.

**Comment by starry69** [comment]
Hmm ig that's actually a nice idea, after bit of thinking I've realised, there have been times when you're saving up for something but you don't have any certain deadline for it in mind, so it makes sense to keep it optional parameter when adding a new goal, one can always add a deadline by editing the goal later on, I'll try doing something about it in upcoming updates. Thanks!

**Comment by Terkyz** [comment]
Sounds good, If it's possible please also adds the option to change an goal with a deadline to one without.
