### ISSUE TITLE
[Feature Request] Remove fractions from some currencies

### ISSUE THREAD

**Issue by Cloudef** [Pool-Of-Tears/GreenStash#63]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

Hello, great app first of all!
I'd love to have fractions removed from some currencies like JPY.

As seen in the screenshot below, the extra `,00` is unneeded noise for JPY. It also makes the "Currently saved ¥,00" look awkard.
![Screenshot_20240111-112425_GreenStash](https://github.com/Pool-Of-Tears/GreenStash/assets/480330/3667f840-db52-46fa-88ca-38093f0f1802)

### Describe the solution you'd like

Remove fractions and show `¥,00` as `¥0`

### How will you/everyone benefit from this feature?

I think the people using the currencies with 0 decimals as listed in this article would benefit
https://docs.adyen.com/development-resources/currency-codes/

**Comment by starry-shivam** [comment]
I see, thanks for linking me list of currencies who use zero decimal, I'll try to fix this in upcoming releases.

**Comment by Cloudef** [comment]
It seems kotlin and java has tools for handling localized currencies already:
https://developer.android.com/reference/kotlin/android/icu/util/Currency
https://stackoverflow.com/questions/13181143/how-can-i-feed-a-iso4217-currency-code-to-a-numberformat
These might help you as well

**Comment by starry-shivam** [comment]
Thats great! thanks again for looking into and finding them out :)
