### ISSUE TITLE
[Feature Request] Remember last filter options 

### ISSUE THREAD

**Issue by Terkyz** [Pool-Of-Tears/GreenStash#64]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

Yes but no, it doesn't affect directly the app, it's just a convenience problem. I wish that when I filter by ascending price that filter remains applied even if I close and reopen the app.

### Describe the solution you'd like

I guess the filter can simply remain applied, and this behavior can be deactivated in the app settings if necessary.

### How will you/everyone benefit from this feature?

As I said, it's just a convenience feature that I use in other apps. I'm sure that other users will be happy with.

### Additional context

Thanks.

**Comment by starry-shivam** [comment]
Makes sense, will add in next release.
