### ISSUE TITLE
[(Yet another) Feature Request] Notes or details of the product or purchase location within the goal

### ISSUE THREAD

**Issue by Terkyz** [Pool-Of-Tears/GreenStash#7]
Nothing very abusive, since this is an app for goals, not for notes. My main idea is that within the goal or when creating a new one there are some spaces for notes or details to add purchase location, name of the store, product webpage, specifications, or a small space for notes

I can also think of a view of [Folders] to have ordered different products or different stores where to buy something, but that's another topic

**Comment by Terkyz** [comment]
> Nothing very abusive, since this is an app for goals, not for notes. My main idea is that within the meta or when creating a new one there are some spaces for notes or details to add purchase location, product webpage, name of the store, specifications, or a small space for notes
> 
> I can also think of a view of [Folders] to have ordered different products or different stores where to buy something, but that's another topic

**Comment by Terkyz** [comment]
> Nothing very abusive, since this is an app for goals, not for notes. My main idea is that within the goal or when creating a new one there are some spaces for notes or details to add purchase location, name of the store, product webpage, specifications, or a small space for notes
> 
> I can also think of a view of [Folders] to have ordered different products or different stores where to buy something, but that's another topic

**Comment by starry69** [comment]
Not abusive at all XD, ig ability to have some notes attached with goals is good idea aswell, maybe we can show notes when user clicks on (i) button where it shows transaction history etc, I'll think about it. Thanks for suggestions!
