### ISSUE TITLE
[Bug]: Stop showing the msg Authentication Succeeded 

### ISSUE THREAD

**Issue by saltsoftdrink** [Pool-Of-Tears/GreenStash#71]
### Steps to reproduce

Turn on biometric 

### Expected behaviour

It should normally turn on without any msg

### Actual behaviour

It should normally turn on without any msg

### Android version

13

### GreenStash version

2.9.0

**Comment by starry-shivam** [comment]
Not really a "bug" but more like minor UX adjustment, anyways will remove that toast message in next version i agree that it's not really needed.
