### ISSUE TITLE
[Feature Request] add a transaction description 

### ISSUE THREAD

**Issue by dodohjk** [Pool-Of-Tears/GreenStash#72]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

Transactions of withdrawals and deposits are rather generic. There is only date and amounts information 

### Describe the solution you'd like

Like a fake bank account I would like a short one line description of the transaction

### How will you/everyone benefit from this feature?

Would allow to give (optionally) more context to how the saving goal was reached 

### Additional context

![Screenshot_20240212_143217_GreenStash](https://github.com/Pool-Of-Tears/GreenStash/assets/13835464/d7035c0e-e476-4e46-ad4d-eaf32480ceae)

**Comment by starry-shivam** [comment]
Yeah I've plans to do some overhaul in this area with ability to change dates aswell instead of just using current timestamp when transaction was added, will add transaction notes aswell when i do that.
