### ISSUE TITLE
[Feature Request] Adding a menu to select lenguage

### ISSUE THREAD

**Issue by SnakeOverflow** [Pool-Of-Tears/GreenStash#8]
So far I've been translating the strings.xml file. And I was wondering, would it be possible to add a function for the app to use a different strings.xml file depending on the language selected? 

That way we would be able to add community translations and have multiple languages on the app. 

So far replacing the file works, but that would still keep the app on a single language.

**Comment by starry69** [comment]
Sure it can be done, also you don't need to replace the translation say you're adding Japanese translation, you just need to create a new `values-ja` folder inside `/app/src/main/res` directory and put your `strings.xml` file inside it, now when you set your device language to Japanese, android will automatically use Japanese string resources for the apps in which it is available. But yeah as i said previously a switch can also be added to manually change language if needed. Feel free to create a PR with your translation file if you want to~

**Comment by SnakeOverflow** [comment]
sure I'll try that, I'll add a PR afterwards.

Thank you

**Comment by SnakeOverflow** [comment]
I got most of the app translated I'm just having trouble finding the location of 5 fields to translate, they weren't in strings.xml or arrays.xml.

1. The Cancel & Done buttons when withdrawing/depositing.
2. Inside on Goal information the Deposited/Withdrawn text field.
3. The: currently saved $x out of $x field .
4. You have until x date(x days)days left.
5. you need to save around  day/week/month field.

Other than that I'm practically done. I'll do a PR once I can finish these.
Thank you.

**Comment by SnakeOverflow** [comment]
Ok I made the PR.

One last question: are the Deposited/Withdrawn text in this image dynamic? line 37 & 41 seem to change the buttons correctly, but these ones don't seem to change.

Thank you.

![Screenshot_20220725-033241](https://user-images.githubusercontent.com/109717184/180777599-15a5f44b-0a4c-4f7b-9f6f-066955181db8.png)
?

**Comment by starry69** [comment]
These are also hardcoded rn, I'll export string resources for them while fixing the adapter thingy.

**Comment by starry69** [comment]
Closing since #9 is merged now
