### ISSUE TITLE
[Feature Request] Make icons more consistent in style, aligning with Material Design 3 guidelines

### ISSUE THREAD

**Issue by chriscross12324** [Pool-Of-Tears/GreenStash#85]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Have all icons migrated to the Material Rounded style

### How will you/everyone benefit from this feature?

Just to bring more consistency

**Comment by starry-shivam** [comment]
The icons I use are mostly from Material Design Icons by Google themselves: (https://fonts.google.com/icons). There are indeed few icons from a different icon pack called Solar Icons, but I don't think they necessarily break the consistency. Their shapes are quite similar, and they look nice in specific places, like the navigation drawer, for example. It gives them a bit of a unique touch, I think.
