### ISSUE TITLE
[Feature Request] Copy text in goal notes with long press

### ISSUE THREAD

**Issue by mrghosti3** [Pool-Of-Tears/GreenStash#94]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

I would like to keep URL or other types of information in one place where I also track progress on the goal. Currently the text that gets saved can be accessed again by editing the goal again. Would like to have an option to quickly copy the text from the notes field.

### Describe the solution you'd like

Copying to clipboard after long pressing the text on notes (after expanding) or having a separate button that copies the note.

### How will you/everyone benefit from this feature?

Less steps in copying the text (URL or search keywords) into clipboard.

**Comment by mrghosti3** [comment]
Could implement this feature quickly. The previous ones are a bit more difficult for me as I'm new to kotlin overall, used to older way (Java and XML) of developing Android apps.

**Comment by starry-shivam** [comment]
Sounds like a good idea. I think adding a copy button here, which is visible after expanding, would be a better idea than long-press, as long-press can collide with the card's collapse UI which happens on single tap.

![IMG_20240406_222029_258](https://github.com/Pool-Of-Tears/GreenStash/assets/58552395/2d81a3dd-f015-45df-abf9-4d6f82c2acdc)

**Comment by mrghosti3** [comment]
How about adding a button on the left of the arrow? This could allow to skip needing to expand the note card.

**Comment by starry-shivam** [comment]
I don't think that would be great from a UX perspective because then it can only be an icon button, which would be very small and easily misclicked, leading to the expansion of the notes card instead of the text being copied. The other solution allows us to have an actual button with a decent size, which cannot be easily misinterpreted. I think something like `(copyIcon "copy")` using `FilledTonalButton()` would look much nicer.

**Comment by mrghosti3** [comment]
Understandable, then a copy button below text sounds like a good way to do. Gonna try and create it then.

ps. Also to clarify, it's a [Filled tonal button](https://developer.android.com/develop/ui/compose/components/button) with an icon or without?

**Comment by starry-shivam** [comment]
Great!

> Also to clarify, it's a Filled tonal button with an icon or without

With, you can probably use something like `Icons.Filled.Copy` combined with `ButtonDefaults.IconSpacing` for placing icon and a text inside `Row()`

I think this could be implemented by preferably overloading or adding two additional parameters in `ExpandableTextCard()`, which is used to show notes. One is for deciding whether we should show a copy button (something like `showCopyButton: Boolean`), and the other is a callback (`onCopyClicked(text)`) which would allow us to handle copying of the text.

**Comment by mrghosti3** [comment]
I think adding an argument (`showCopyButton`) will be enough for this case. It's best to do the simplest method now, and change to more advanced later if there comes a use-case for that.

On other note, check the available [Icons](https://fonts.google.com/icons?icon.query=Copy&icon.platform=web) and think the `ContentCopy` one is the right one.

You can check it out here: https://github.com/mrghosti3/GreenStash/tree/note-copy

**Comment by starry-shivam** [comment]
> I think adding an argument (showCopyButton) will be enough for this case. It's best to do the simplest method now, and change to more advanced later if there comes a use-case for that

Sure! works for me :)

> On other note, check the available Icons and think the ContentCopy one is the right one.

Yeah looks good! We can go ahead with this.

> You can check it out here: https://github.com/mrghosti3/GreenStash/tree/note-copy

Feel free to create a PR if you think it's ready. I'll review it tomorrow since it's late night where I am.

**Comment by mrghosti3** [comment]
Okay, will create a PR later. Have a great evening.
